(define (midi-read-file filename)
  (if (file-exists? filename)
      (let* ((port (open-binary-input-file filename))
             (first-two-bytes (read-u8vector 2 port))
             (second-two-bytes (read-u8vector 2 port)))
        (display first-two-bytes)
        (display second-two-bytes))
      (error "midi-read-file: non-existant file" filename)))
