* chicken-midi
** Synopsis
MIDI-related functions for Chicken Scheme
** Features
 * read MIDI files
** Procedures
*** midi-read-file FILENAME
Note: Only the MIDI file header is read as of version 0.1
** TODO
*** Read MIDI tracks
*** Write MIDI file
** License
Copyright (C) 2020 - Sergey Goldgaber

This file is part of chicken-midi.
chicken-midi is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

chicken-midi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with chicken-midi.  If not, see <http://www.gnu.org/licenses/>.
** Version history
 * 0.1 - Initial release for Chicken 5
